-- USE CREATE TABLESPACE FOR CREATE YOUR OWN TABLESPACE
-- SUFFIX _I IN THE END DEFINES TABLESPACE FOR INDEXES

CREATE TABLE TBL_COUNTRY (
  COUNTRY  VARCHAR(15) NOT NULL,
  CURRENCY VARCHAR(10) NOT NULL
) TABLESPACE TS_EMPLOYEE;

ALTER TABLE TBL_COUNTRY 
  ADD CONSTRAINT PK_COUNTRY$COUNTRY
  PRIMARY KEY(COUNTRY)
  USING INDEX 
  TABLESPACE TS_EMPLOYEE_I;

CREATE TABLE TBL_CUSTOMER (
  CUST_NO        INT4        NOT NULL,
  CUSTOMER       VARCHAR(25) NOT NULL,
  CONTACT_FIRST  VARCHAR(15) NULL,
  CONTACT_LAST   VARCHAR(20) NULL,
  PHONE_NO       VARCHAR(20) NULL,
  ADDRESS_LINE1  VARCHAR(30) NULL,
  ADDRESS_LINE2  VARCHAR(30) NULL,
  CITY           VARCHAR(25) NULL,
  STATE_PROVINCE VARCHAR(15) NULL,
  COUNTRY        VARCHAR(15) NULL,
  POSTAL_CODE    VARCHAR(12) NULL,
  ON_HOLD        BPCHAR(1)   NULL DEFAULT NULL::BPCHAR
) TABLESPACE TS_EMPLOYEE;

ALTER TABLE TBL_CUSTOMER 
  ADD CONSTRAINT PK_CUSTOMER$CUST_NO
  PRIMARY KEY(CUST_NO)
  USING INDEX
  TABLESPACE TS_EMPLOYEE_I;

ALTER TABLE TBL_CUSTOMER
  ADD CONSTRAINT FK_CUSTOMER$COUNTRY
  FOREIGN KEY(COUNTRY)
  REFERENCES TBL_COUNTRY(COUNTRY) ON DELETE CASCADE;

CREATE INDEX IDX_CUSTOMER$COUNTRY
  ON TBL_CUSTOMER(COUNTRY)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_CUSTOMER$CUSTOMER 
  ON TBL_CUSTOMER(CUSTOMER)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_CUSTOMER$REGIEN 
  ON TBL_CUSTOMER (COUNTRY, CITY)
TABLESPACE TS_EMPLOYEE_I;

CREATE TABLE TBL_JOB (
  JOB_CODE        VARCHAR(5)     NOT NULL,
  JOB_GRADE       INT2           NOT NULL,
  JOB_COUNTRY     VARCHAR(25)    NOT NULL,
  JOB_TITLE       VARCHAR(25)    NOT NULL,
  MIN_SALARY      NUMERIC(10, 2) NOT NULL DEFAULT 0,
  MAX_SALARY      NUMERIC(10, 2) NOT NULL DEFAULT 0,
  JOB_REQUIREMENT BYTEA NULL,
  LANGUAGE_REQ    TEXT NULL
) TABLESPACE TS_EMPLOYEE;

ALTER TABLE TBL_JOB
  ADD CONSTRAINT PK_JOB$CODEGRADECNT
  PRIMARY KEY(JOB_CODE, JOB_GRADE, JOB_COUNTRY)
  USING INDEX
  TABLESPACE TS_EMPLOYEE_I;

ALTER TABLE TBL_JOB
  ADD CONSTRAINT FK_JOB$COUNTRY
  FOREIGN KEY(JOB_COUNTRY)
  REFERENCES TBL_COUNTRY(COUNTRY) ON DELETE CASCADE;

CREATE INDEX IDX_JOB$MAXSALX 
  ON TBL_JOB(JOB_COUNTRY DESC, MAX_SALARY DESC)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_JOB$MINSALX 
  ON TBL_JOB(JOB_COUNTRY, MIN_SALARY)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_JOB$JOB_COUNTRY 
  ON TBL_JOB(JOB_COUNTRY)
TABLESPACE TS_EMPLOYEE_I;

CREATE TABLE TBL_DEPARTMENT (
  DEPT_NO    BPCHAR(3)      NOT NULL,
  DEPARTMENT VARCHAR(25)    NOT NULL,
  HEAD_DEPT  BPCHAR(3)      NULL,
  MNGR_NO    INT2           NULL,
  BUDGET     NUMERIC(12, 2) NULL DEFAULT 50000,
  LOCATION   VARCHAR(15)    NULL,
  PHONE_NO   VARCHAR(20)    NULL DEFAULT '555-1234'::CHARACTER VARYING
) TABLESPACE TS_EMPLOYEE;

ALTER TABLE TBL_DEPARTMENT 
  ADD CONSTRAINT PK_DEPARTMENT$DEPT_NO
  PRIMARY KEY(DEPT_NO)
  USING INDEX
TABLESPACE TS_EMPLOYEE_I;

ALTER TABLE TBL_DEPARTMENT
  ADD CONSTRAINT UK_DEPARTMENT$DEPARTMENT 
  UNIQUE(DEPARTMENT)
  USING INDEX
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_DEPARTMENT$BUDGETX 
  ON TBL_DEPARTMENT(BUDGET DESC)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_DEPARTMENT$MNGR_NO
  ON TBL_DEPARTMENT(MNGR_NO)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_DEPARTMENT$HEAD_DEPT
  ON TBL_DEPARTMENT(HEAD_DEPT)
TABLESPACE TS_EMPLOYEE_I;

CREATE TABLE TBL_EMPLOYEE (
  EMP_NO      INT2           NOT NULL,
  FIRST_NAME  VARCHAR(15)    NOT NULL,
  LAST_NAME   VARCHAR(20)    NOT NULL,
  PHONE_EXT   VARCHAR(4)     NULL,
  HIRE_DATE   TIMESTAMP      NOT NULL DEFAULT '2022-12-27 18:25:47.350745'::TIMESTAMP WITHOUT TIME ZONE,
  DEPT_NO     BPCHAR(3)      NOT NULL,
  JOB_CODE    VARCHAR(5)     NOT NULL,
  JOB_GRADE   INT2           NOT NULL,
  JOB_COUNTRY VARCHAR(15)    NOT NULL,
  SALARY      NUMERIC(10, 2) NOT NULL DEFAULT 0,
  FULL_NAME   VARCHAR(37)    NULL
) TABLESPACE TS_EMPLOYEE;

ALTER TABLE TBL_EMPLOYEE
  ADD CONSTRAINT PK_EMPLOYEE$EMP_NO
  PRIMARY KEY(EMP_NO)
  USING INDEX
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_EMPLOYEE$NAME
  ON TBL_EMPLOYEE(LAST_NAME, FIRST_NAME)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_EMPLOYEE$DEPT_NO
  ON TBL_EMPLOYEE(DEPT_NO)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_EMPLOYEE$CODEGRADECNT
  ON TBL_EMPLOYEE(JOB_CODE, JOB_GRADE, JOB_COUNTRY)
TABLESPACE TS_EMPLOYEE_I;

CREATE TABLE TBL_EMPLOYEE_PROJECT (
  EMP_NO   INT2 NOT NULL,
  PROJ_ID BPCHAR(5) NOT NULL
) TABLESPACE TS_EMPLOYEE;

ALTER TABLE TBL_EMPLOYEE_PROJECT 
  ADD CONSTRAINT PK_EMP_NO_PROJ_ID
  PRIMARY KEY(EMP_NO, PROJ_ID)
  USING INDEX
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_EMP_PROJ$EMP_NO
  ON TBL_EMPLOYEE_PROJECT(EMP_NO)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_EMP_PROJ$PROJ_ID
  ON TBL_EMPLOYEE_PROJECT(PROJ_ID)
TABLESPACE TS_EMPLOYEE_I;

CREATE TABLE TBL_PROJ_DEPT_BUDGET (
  FISCAL_YEAR      INT4           NOT NULL,
  PROJ_ID          BPCHAR(5)      NOT NULL,
  DEPT_NO          BPCHAR(3)      NOT NULL,
  QUART_HEAD_CNT   INT4           NULL,
  PROJECTED_BUDGET NUMERIC(12, 2) NULL DEFAULT 50000
) TABLESPACE TS_EMPLOYEE;

ALTER TABLE TBL_PROJ_DEPT_BUDGET
  ADD CONSTRAINT PK_PROJ_DEPT_BUDGET$FY_PROJID_DEPTNO
  PRIMARY KEY(FISCAL_YEAR, PROJ_ID, DEPT_NO)
  USING INDEX
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_PROJ_DEPT_BUDGET$PROJ_ID
  ON TBL_PROJ_DEPT_BUDGET(PROJ_ID)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_PROJ_DEPT_BUDGET$DEPT_NO
  ON TBL_PROJ_DEPT_BUDGET(DEPT_NO)
TABLESPACE TS_EMPLOYEE_I;

CREATE TABLE TBL_PROJECT (
  PROJ_ID     BPCHAR(5)   NOT NULL,
  PROJ_NAME   VARCHAR(20) NOT NULL,
  PROJ_DESC   BYTEA       NULL,
  TEAM_LEADER INT2        NULL,
  PRODUCT     VARCHAR(12) NOT NULL DEFAULT 'SOFTWARE'::CHARACTER VARYING
) TABLESPACE TS_EMPLOYEE;

ALTER TABLE TBL_PROJECT
  ADD CONSTRAINT PK_PROJECT$PROJ_ID
  PRIMARY KEY(PROJ_ID)
  USING INDEX
TABLESPACE TS_EMPLOYEE_I;

ALTER TABLE TBL_PROJECT
  ADD CONSTRAINT UK_PROJECT$PROJ_NAME
  UNIQUE(PROJ_NAME)
  USING INDEX
TABLESPACE TS_EMPLOYEE_I;

ALTER TABLE TBL_PROJECT
  ADD CONSTRAINT UK_PROJECT$PRODTYPEX
  UNIQUE(PRODUCT, PROJ_NAME)
  USING INDEX
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_PROJECT$TEAM_LEADER
  ON TBL_PROJECT(TEAM_LEADER)
TABLESPACE TS_EMPLOYEE_I;

CREATE TABLE TBL_SALARY_HISTORY (
  EMP_NO         INT2           NOT NULL,
  CHANGE_DATE    TIMESTAMP      NOT NULL DEFAULT '2022-12-27 19:21:09.081499'::TIMESTAMP WITHOUT TIME ZONE,
  UPDATER_ID     VARCHAR(20)    NOT NULL,
  OLD_SALARY     NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PERCENT_CHANGE FLOAT8         NOT NULL DEFAULT 0,
  NEW_SALARY     FLOAT8         NULL
) TABLESPACE TS_EMPLOYEE;

ALTER TABLE TBL_SALARY_HISTORY
  ADD CONSTRAINT PK_SALARY_HISTORY$CHANGE
  PRIMARY KEY(EMP_NO, CHANGE_DATE, UPDATER_ID)
  USING INDEX
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_SALARY_HISTORY$CHANGE_DATE
  ON TBL_SALARY_HISTORY(CHANGE_DATE DESC)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_SALARY_HISTORY$EMP_NO
  ON TBL_SALARY_HISTORY(EMP_NO)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_SALARY_HISTORY$UPDATER_ID
  ON TBL_SALARY_HISTORY(UPDATER_ID)
TABLESPACE TS_EMPLOYEE_I;

CREATE TABLE TBL_SALES (
  PO_NUMBER    BPCHAR(8)      NOT NULL,
  CUST_NO      INT4           NOT NULL,
  SALES_REP    INT2           NULL,
  ORDER_STATUS VARCHAR(15)    NOT NULL DEFAULT 'NEW'::CHARACTER VARYING,
  ORDER_DATE   TIMESTAMP      NOT NULL DEFAULT '2022-12-27 19:21:20.701627'::TIMESTAMP WITHOUT TIME ZONE,
  SHIP_DATE    TIMESTAMP      NULL,
  DATE_NEEDED  TIMESTAMP      NULL,
  PAID         BPCHAR(1)      NULL DEFAULT 'N'::BPCHAR,
  QTY_ORDERED  INT4           NOT NULL DEFAULT 1,
  TOTAL_VALUE  NUMERIC(9, 2)  NOT NULL,
  DISCOUNT     FLOAT8         NOT NULL DEFAULT 0,
  ITEM_TYPE    VARCHAR(12)    NOT NULL DEFAULT 'SOFTWARE'::CHARACTER VARYING,
  AGED         NUMERIC(18, 9) NULL
) TABLESPACE TS_EMPLOYEE;

ALTER TABLE TBL_SALES
  ADD CONSTRAINT PK_SALES$PO_NUMBER
  PRIMARY KEY(PO_NUMBER)
  USING INDEX
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_SALES$DATE_NEEDED
  ON TBL_SALES(DATE_NEEDED)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_SALES$QTYX
  ON TBL_SALES(ITEM_TYPE, QTY_ORDERED)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_SALES$CUST_NO
  ON TBL_SALES(CUST_NO)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_SALES$SALES_REP
  ON TBL_SALES(SALES_REP)
TABLESPACE TS_EMPLOYEE_I;

CREATE INDEX IDX_SALES$SALE_STAT
  ON TBL_SALES(ORDER_STATUS, PAID)
TABLESPACE TS_EMPLOYEE_I;

ALTER TABLE TBL_DEPARTMENT 
  ADD CONSTRAINT FK_DEPARTMENT$HEAD_DEPT 
  FOREIGN KEY (HEAD_DEPT) 
  REFERENCES TBL_DEPARTMENT(DEPT_NO) ON DELETE CASCADE;

ALTER TABLE TBL_DEPARTMENT 
  ADD CONSTRAINT FK_DEPARTMENT$EMP_NO 
  FOREIGN KEY (MNGR_NO) 
  REFERENCES TBL_EMPLOYEE(EMP_NO) ON DELETE CASCADE;

ALTER TABLE TBL_EMPLOYEE 
  ADD CONSTRAINT FK_EMPLOYEE$DEPT_NO 
  FOREIGN KEY (DEPT_NO) 
  REFERENCES TBL_DEPARTMENT(DEPT_NO) ON DELETE CASCADE;

ALTER TABLE TBL_EMPLOYEE 
  ADD CONSTRAINT FK_EMPLOYEE$JOB_QUALITY 
  FOREIGN KEY (JOB_CODE, JOB_GRADE, JOB_COUNTRY) 
  REFERENCES TBL_JOB(JOB_CODE, JOB_GRADE, JOB_COUNTRY) ON DELETE CASCADE;

ALTER TABLE TBL_EMPLOYEE_PROJECT 
  ADD CONSTRAINT FK_EMPLOYEE_PROJECT$EMP_NO 
  FOREIGN KEY (EMP_NO) 
  REFERENCES TBL_EMPLOYEE(EMP_NO) ON DELETE CASCADE;

ALTER TABLE TBL_EMPLOYEE_PROJECT 
  ADD CONSTRAINT FK_EMPLOYEE_PROJECT$PROJ_ID 
  FOREIGN KEY (PROJ_ID) 
  REFERENCES TBL_PROJECT(PROJ_ID) ON DELETE CASCADE;

ALTER TABLE TBL_PROJ_DEPT_BUDGET 
  ADD CONSTRAINT FK_PROJ_DEPT_BUDGET$DEPT_NO 
  FOREIGN KEY (DEPT_NO) 
  REFERENCES TBL_DEPARTMENT(DEPT_NO) ON DELETE CASCADE;

ALTER TABLE TBL_PROJ_DEPT_BUDGET 
  ADD CONSTRAINT FK_PROJ_DEPT_BUDGET$PROJ_ID 
  FOREIGN KEY (PROJ_ID) 
  REFERENCES TBL_PROJECT(PROJ_ID) ON DELETE CASCADE;

ALTER TABLE TBL_PROJECT 
  ADD CONSTRAINT FK_PROJECT$EMP_NO 
  FOREIGN KEY (TEAM_LEADER) 
  REFERENCES TBL_EMPLOYEE(EMP_NO) ON DELETE CASCADE;

ALTER TABLE TBL_SALARY_HISTORY 
  ADD CONSTRAINT FK_SALARY_HISTORY$EMP_NO 
  FOREIGN KEY (EMP_NO) 
  REFERENCES TBL_EMPLOYEE(EMP_NO) ON DELETE CASCADE;

ALTER TABLE TBL_SALES 
  ADD CONSTRAINT FK_SALES$CUST_NO 
  FOREIGN KEY (CUST_NO) 
  REFERENCES TBL_CUSTOMER(CUST_NO) ON DELETE CASCADE;

ALTER TABLE TBL_SALES 
  ADD CONSTRAINT FK_SALES$EMP_NO 
  FOREIGN KEY (SALES_REP) 
  REFERENCES TBL_EMPLOYEE(EMP_NO) ON DELETE CASCADE;