INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p1','Сабона Плюс','Казань','335-23-69');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p2','Арт-Комплект','Батайск','251-23-40');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p3','Металлиндустрия','Москва','835-38-97');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p4','Ресурс-Капитал','Екатеринбург','598-20-88');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p5','Торговый дом Уралкварц','Ростов-на-Дону','519-97-96');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p6','Оникс','Таганрог','459-98-48');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p7','Ремстройсервис','Санкт-Петербург','860-63-43');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p8','МедиаСервис','Москва',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p9','Аргумент','Батайск','778-92-86');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p10','Прайм-Информ','Екатеринбург',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p11','О Г М','Шахты','215-81-58');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p12','НПП Модус-М','Казань','178-89-53');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p13','Стройтехносфера','Екатеринбург','624-13-32');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p14','Промснаб','Санкт-Петербург','284-65-11');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p15','Элегия','Казань','876-96-83');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p16','Интра-Трейд','Ростов-на-Дону','916-93-10');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p17','УралВагонМеханика','Таганрог','199-26-23');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p18','Шина','Шахты','238-97-24');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p19','Строй-Астер','Санкт-Петербург','357-95-16');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p20','Автодиск','Батайск',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p21','Черметопторг','Шахты','556-31-71');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p22','Омега','Новосибирск','304-51-38');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p23','ЭКСИМ','Таганрог',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p24','Троица','Новосибирск','901-17-10');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p25','МЕТПРОМСЕРВИС','Москва','705-77-65');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p26','Уральская Ассоциация Клининга','Санкт-Петербург','835-37-69');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p27','Рекламное обеспечение бизнеса','Краснодар','560-17-85');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p28','Вектор','Азов','375-78-42');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p29','Ривьера','Азов','568-25-44');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p30','Радуга','Таганрог','606-84-64');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p31','Промышленная безопасность','Таганрог','498-38-95');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p32','СтройТрансАвто','Екатеринбург','373-48-72');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p33','ЕвроТорг','Екатеринбург','559-23-46');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p34','ТрансСервисВосток','Санкт-Петербург','243-62-49');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p35','МонтажСтройИнвест','Батайск',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p36','Промторгснаб','Новосибирск','333-35-13');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p37','Уралсервиcопт','Батайск','215-51-73');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p38','Бетстрой','Санкт-Петербург','323-75-33');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p39','Лига','Екатеринбург','115-86-46');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p40','АВ-Маркет','Ростов-на-Дону','259-67-86');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p41','Альянс','Батайск','896-94-20');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p42','Снабкомплект','Таганрог','363-14-31');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p43','Золотой скорпион','Санкт-Петербург','924-62-26');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p44','Приам','Новосибирск','733-89-22');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p45','ЭраСтрой','Шахты','307-67-38');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p46','Урал','Батайск','535-79-73');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p47','Веста','Екатеринбург','541-78-46');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p48','ТеплоЭнергоСтрой','Таганрог','281-44-44');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p49','Трубметком','Азов','334-98-82');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p50','Профи','Шахты','482-13-80');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p51','Урал-Альянс','Новосибирск',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p52','Универсал-Снаб','Новосибирск','458-20-65');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p53','Крокус','Краснодар','275-92-48');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p54','Андромеда','Екатеринбург','890-28-83');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p55','Салма','Таганрог',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p56','Маяк','Новосибирск','414-10-90');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p57','Гамма-Урал','Казань',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p58','Вегус','Москва',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p59','МИТМ','Москва',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p60','ВЭЛТКОМ','Таганрог','951-33-76');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p61','Домком','Шахты','167-89-35');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p62','Лига-Кэпитал','Новосибирск',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p63','Спецпром','Батайск','210-12-64');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p64','ТИСС','Батайск',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p65','Механизированная колонна-12','Екатеринбург',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p66','РЕАЛКОМ','Новосибирск','538-77-77');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p67','РЕАЛКОМ-ЕК','Москва','797-80-92');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p68','Уралметторг','Екатеринбург',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p69','Аква-Трейд','Санкт-Петербург','343-13-98');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p70','Торг Сервис','Екатеринбург','307-51-25');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p71','Орикс','Санкт-Петербург','152-94-38');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p72','Лэтос','Батайск','412-96-87');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p73','МВК','Санкт-Петербург','630-17-30');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p74','Строитель','Екатеринбург','419-34-59');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p75','Среднерусский центр спортивного ориентирования','Ростов-на-Дону','570-53-34');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p76','РУСИЧ','Новосибирск','407-86-75');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p77','Монтажник-2','Батайск',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p78','Платановая аллея','Батайск','229-52-56');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p79','Усольский Художник','Москва','723-26-21');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p80','ПАТРИОТ','Шахты','272-80-75');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p81','Луч - 7','Шахты','959-68-14');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p82','Исток','Москва','723-28-92');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p83','ДАНИЛЫЧ','Санкт-Петербург','792-88-95');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p84','Игл','Санкт-Петербург',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p85','Нэвис+','Казань','156-24-42');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p86','Стройсервис','Краснодар','395-78-41');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p87','ЭМО','Краснодар','388-46-13');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p88','ЛенСтройТоргСервис','Азов',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p89','КЛИНЛЭНД','Екатеринбург','878-19-70');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p90','МЕЦЕНАТ','Санкт-Петербург',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p91','АЛЕТЕКС','Ростов-на-Дону',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p92','КВАДРО','Новосибирск','442-57-61');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p93','Гигабит','Москва','312-59-27');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p94','Кубань Ксилолит','Таганрог','219-28-36');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p95','АВТЕКС-ГРУПП','Азов','128-32-44');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p96','Рыбокомбинат Волгоградский','Москва','387-35-11');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p97','Регион Бизнес Альянс','Ростов-на-Дону',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p98','СТРОЙРЕАЛПРЕСТИЖ','Шахты','399-64-49');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p99','АРВЕСТ','Таганрог',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p100','ЖБИ Сервис','Екатеринбург','718-11-62');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p101','Реал - НН','Батайск','733-37-31');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p102','Бар-С','Краснодар','129-91-90');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p103','Проспект-В','Азов','243-77-43');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p104','Драйзэн','Таганрог',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p105','ВОК - 72','Казань','655-81-22');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p106','Лагуна','Краснодар','572-38-49');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p107','Уралторг','Ростов-на-Дону','742-74-45');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p108','ГрафГаз','Азов','847-89-43');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p109','Регионсерия','Ростов-на-Дону','335-39-81');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p110','Центр','Санкт-Петербург','749-22-88');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p111','Срочная Американская Экспресс чистка','Ростов-на-Дону','156-79-71');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p112','АйСиком мастер','Екатеринбург','815-80-88');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p113','МАШТЕХПРОДУКТ','Казань','960-27-31');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p114','Клин Ленд','Санкт-Петербург','779-86-96');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p115','Астроник','Батайск','875-65-14');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p116','Уралнефтьсервис','Шахты',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p117','МЕХАНИК','Новосибирск','168-26-75');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p118','Стелла','Шахты','434-47-50');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p119','Новые Решения','Шахты','159-45-25');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p120','Волжский Капитал','Екатеринбург','590-63-55');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p121','ВИТНА','Азов','116-54-84');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p122','Ореол С','Шахты',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p123','НВЛ','Азов','982-10-78');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p124','Орлов и Компания','Шахты','193-90-74');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p125','Министерство','Санкт-Петербург',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p126','ГрандАвто','Санкт-Петербург','260-43-21');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p127','ВариантСтрой','Москва','567-16-52');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p128','Урал-Торг','Москва','668-53-89');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p129','Металлинвест','Санкт-Петербург',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p130','АБСТехно','Екатеринбург','991-91-10');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p131','Декарт','Санкт-Петербург','736-28-68');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p132','Орион','Москва','678-46-42');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p133','ДОГОДА','Шахты',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p134','Горизонт','Азов','464-49-54');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p135','Забота','Таганрог','464-51-67');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p136','ТРАНСМЕХ','Таганрог',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p137','Элана','Ростов-на-Дону','409-89-30');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p138','Водоканал','Шахты','937-85-91');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p139','Барс','Ростов-на-Дону','124-49-41');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p140','Спецторг','Казань',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p141','Рыбацкая деревня','Шахты','983-25-15');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p142','ЭЛЕКТРОМАШ','Шахты','202-85-78');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p143','Палкинский','Ростов-на-Дону','712-31-77');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p144','Управдом','Таганрог',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p145','Тёплый Дом','Санкт-Петербург','513-94-92');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p146','Чаплыгинский','Батайск','886-14-76');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p147','Опытно-Механический завод','Таганрог','432-41-10');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p148','ТЕЗА-ВН','Шахты','925-96-95');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p149','Теза-Н','Краснодар','356-49-29');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p150','ЛУЧ-3','Батайск',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p151','Автотехсервис','Шахты','272-11-57');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p152','Дельта-С','Екатеринбург',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p153','Мединфос','Краснодар','820-34-71');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p154','Кентавр','Санкт-Петербург','642-25-96');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p155','Техцентр','Таганрог','242-92-36');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p156','Петровские дачи','Шахты','854-44-53');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p157','ЭнергоАктив','Новосибирск','185-16-89');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p158','Унимерская слобода','Азов','550-56-34');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p159','Гольдберг-Софт','Екатеринбург',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p160','ВИКТОРИЯ-Л','Казань',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p161','Энергетик','Екатеринбург','656-83-43');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p162','ВЫМПЕЛ','Санкт-Петербург','298-76-89');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p163','Призма','Шахты','443-78-13');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p164','А-Я','Москва','685-84-52');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p165','Загородный 45','Краснодар','845-75-63');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p166','БСУ','Ростов-на-Дону','265-17-28');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p167','Академия Бильярда','Санкт-Петербург','311-60-97');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p168','Эскорт-медиа','Таганрог','835-67-30');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p169','Паритет','Новосибирск',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p170','Продвижение','Краснодар','191-40-58');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p171','Дельта','Батайск','158-55-68');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p172','Строй-Альянс','Краснодар','461-48-36');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p173','Интерком','Шахты','991-19-53');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p174','АКСЕЛЬ','Казань','799-24-83');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p175','Финпромснаб','Казань','421-27-65');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p176','Кит','Краснодар','866-91-15');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p177','ПЕРЕСВЕТ','Москва','422-37-44');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p178','Рекаунт','Батайск','515-81-26');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p179','Адамант','Таганрог','900-64-16');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p180','Лаксар','Батайск','825-24-12');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p181','Эдельвейс','Краснодар','953-59-44');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p182','Еврокласс-Урал','Краснодар','553-98-83');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p183','Инстрэл','Москва','434-57-86');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p184','Лес-Пром','Санкт-Петербург','131-64-23');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p185','СтройМатериалы','Казань','406-89-70');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p186','Нивад','Батайск','697-97-42');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p187','Фарфора Сысерти','Краснодар',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p188','Авианта','Новосибирск','743-83-55');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p189','Астон Консалтинг','Екатеринбург','764-62-30');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p190','Тритон','Казань','449-18-34');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p191','БЕСТ','Таганрог','421-67-71');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p192','Промбетон','Батайск','638-95-67');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p193','Суводское','Москва','865-28-93');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p194','Автосервис №1','Батайск','653-90-68');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p195','Техноком','Казань','160-26-71');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p196','РИР','Батайск','236-54-17');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p197','Обнорское','Казань','168-17-27');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p198','КВТ','Казань','855-45-35');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p199','Бриз','Новосибирск','594-43-62');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p200','Олимпик-Транс','Новосибирск',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p201','Ника LTD','Ростов-на-Дону','680-16-88');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p202','ТРАНСОЙЛ','Санкт-Петербург','488-30-66');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p203','МИГ','Екатеринбург',NULL);
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p204','Кубаньтрансстройсервис','Краснодар','387-88-55');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p205','Подъёмэкспертсервис','Ростов-на-Дону','468-45-74');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p206','Мехпромстрой-ЮГ','Шахты','387-62-31');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p207','Техинсервис','Краснодар','262-35-19');
INSERT INTO tbl_agent (id_ag,name_ag,town,phone) VALUES ('p208','Азимут +','Ростов-на-Дону','987-91-44');


INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т1','Шариковая ручка (6 шт)','уп');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т2','Гелевая ручка (6 шт)','уп');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т3','Маркер','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т4','Картон','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т5','Дневник','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т6','Калька','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т7','Копировальная бумага','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т8','Линейка','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т9','Транспортир','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т10','Циркуль','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т11','Ластик','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т12','Степлер','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т13','Скобы для степлера (100 шт)','уп');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т14','Антистеплер','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т15','Скрепка (10 шт)','уп');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т16','Булавка (8 шт)','уп');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т17','Скоросшиватель','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т18','Файлы (25 шт)','уп');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т19','Конверт','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т20','Подставка для книг','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т21','Набор закладок (5 шт)','уп');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т22','Обложка для книг (3 шт)','уп');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т23','Канцелярский нож','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т24','Точилка для карандашей','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т25','Ножницы','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т26','Дырокол','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т27','Скотч','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т28','Изолента','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т29','Клей-карандаш','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т30','Клей ПВА','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т31','Набор стикеров (50 шт)','уп');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т32','Пластилин','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т33','Гуашь','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т34','Акварель','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т35','Кисть','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т36','Мел','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т37','Пастель','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т38','Календарь','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т39','Калькулятор','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т40','Корректор','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т41','Фломастер (6 шт)','уп');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т42','Школьный пенал','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т43','Ватман','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т44','Глобус','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т45','Лупа','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т46','Кнопка','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т55','Рюкзак','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т47','Трафарет','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т48','Грамота','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т49','Механический карандаш','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т50','Зажим для бумаги','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т51','Бейджик','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т52','Настенная карта','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т53','Визитница','шт');
INSERT INTO tbl_goods (id_goods,nomenclature,measure) VALUES ('Т54','Портфель','шт');


INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С1','Склад 4','Москва');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С2','Склад ООО Бобер','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С3','Склад 19','Москва');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С4','Склад ООО Поиск','Шахты');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С5','Склад 20','Краснодар');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С6','Склад на ул. Мира','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С7','Склад 22','Екатеринбург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С8','Склад 7','Новосибирск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С9','Склад на ул. Сосновая','Екатеринбург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С10','Склад 13','Азов');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С11','Склад ИП Иванов','Екатеринбург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С12','Склад 14','Екатеринбург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С13','Склад 25','Ростов-на-Дону');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С14','Склад ООО ВКР','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С15','Склад на ул. Комарова','Казань');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С16','Склад на ул. Заречная','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С17','Склад на ул. Колхозная','Азов');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С18','Склад ПАО Магнит','Таганрог');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С19','Склад 15','Батайск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С20','Склад ООО ДАШЛЕШ','Краснодар');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С21','Склад ООО Тракторист','Краснодар');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С22','Склад 11','Азов');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С23','Склад ИП Петров','Шахты');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С24','Склад на ул. Горизонтальная','Ростов-на-Дону');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С25','Склад на ул. Параллельная','Ростов-на-Дону');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С26','Склад 5','Казань');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С27','Склад 10','Новосибирск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С28','Склад ПАО Сбербанк','Батайск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С29','Склад 8','Таганрог');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С30','Склад ИП Лебовски','Казань');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С31','Склад ПАО МТС','Москва');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С32','Склад на ул. Южная','Новосибирск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С33','Склад ПАО Ренессанс','Екатеринбург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С34','Склад на ул. Садовая','Новосибирск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С35','Склад 23','Москва');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С36','Склад ПАО Лапки и ушки','Новосибирск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С37','Склад ООО Гроза','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С38','Склад ООО Мотылек','Шахты');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С39','Склад 9','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С40','Склад 6','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С41','Склад на ул. Майская','Батайск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С42','Склад ИП Троцкий','Ростов-на-Дону');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С43','Склад на ул. Озерная','Краснодар');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С44','Склад на ул. Чапаева','Новосибирск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С45','Склад 21','Таганрог');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С46','Склад на ул. Трудовая','Екатеринбург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С47','Склад ПАО Газпром','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С48','Склад 24','Новосибирск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С49','Склад на ул. Подгорная','Шахты');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С50','Склад 12','Новосибирск');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С51','Склад 16','Екатеринбург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С52','Склад на ул. Фрунзе','Шахты');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С53','Склад на ул. Горького','Таганрог');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С54','Склад на ул. Березовая','Таганрог');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С55','Склад 17','Шахты');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С56','Склад на ул. Шоссейная','Краснодар');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С57','Склад 18','Таганрог');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С58','Склад на ул. Полевая','Казань');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С59','Склад ПАО Самокат','Таганрог');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С60','Склад ООО Кловер','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С61','Склад ИП Ванин','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С62','Склад ИП Сальников','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С63','Склад на ул. Вертикальная','Краснодар');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С64','Склад на ул. Чехова','Санкт-Петербург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С65','Склад ИП Дробиков','Екатеринбург');
INSERT INTO tbl_warehouse (id_wh,"name",town) VALUES ('С66','Склад на ул. Восточная','Москва');
